version: "3.1"

services:
  form-builder-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: form-builder-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: form-builder
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - form-builder-db:/var/lib/mysql

volumes:
  form-builder-db:
